name: CI for SonarQube Source Code with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Installer Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2


      # Lancer SonarQube 
      - name: Run SonarQube
        run: ./gradlew sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.organization=mahdi01x
